### PR TITLE
[KIECLOUD-448] - Provide automated way to update product version on R…

### PR DESCRIPTION
**Pull request by spolti**
…HPAM and RHDM repositories
 
See: https://issues.redhat.com/browse/KIECLOUD-448

Signed-off-by: spolti <fspolti@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [x] Pull Request title is properly formatted: `[RHDM-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Attached commits represent units of work and are properly formatted
- [x] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [x] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Review by jakubschwan — COMMENTED** [review]
lgtm

**Review by msmagnanijr — APPROVED** [review]

**Review by Kaitou786 — DISMISSED** [review]

**Comment by Kaitou786** [comment]
Not sure if this should be updated with the script:
Screenshot from 2021-01-12 18-04-55

**Comment by spolti** [comment]
it shouldn't, nice catch!

**Review by Kaitou786 — APPROVED** [review]
Works nicely :)

**Review by Kaitou786 — APPROVED** [review]

**Pull request merged**
