### PR TITLE
Update install

### PR DESCRIPTION
**Pull request by jesuino**
Why not use a touch here like it is done in the kie server image? sending PR because issues are not open.

### CODE REVIEW

**Comment by errantepiphany** [comment]
@jesuino, is there a JIRA this PR can be associated with please?
@spolti, FYI.

**Comment by spolti** [comment]
At first look I think it is ok, I just need to check if no garbage will be left (decision-central.war.dodeploy file).

**Comment by jesuino** [comment]
@errantepiphany Where do you I file a JIRA: RHDM or CLOUD?

**Comment by spolti** [comment]
rhdm

**Comment by spolti** [comment]
If we just touch a new file the old one still there:

`Scenario: file decision-central.war.dodeploy should not exist                              # features/image/decisioncentral.feature:13
    When container is ready                                                                  # steps/container_steps.py:13 1.618s
    Then file /opt/eap/standalone/deployments/decision-central.war.dodeploy should not exist # steps/steps.py:226 0.112s
      Traceback (most recent call last):
        File "/usr/lib/python2.7/site-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/usr/lib/python2.7/site-packages/behave/model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "/data/dev/sources/rhdm-7-image/decisioncentral/target/test/steps/steps.py", line 235, in check_file_not_exists
          raise Exception("File %s exists" % file_name)
      Exception: File /opt/eap/standalone/deployments/decision-central.war.dodeploy exists
`

In that case, if touch is used, we need to remove and create a new file, which means, 2 operations and 2 inodes being used, against 1 operation and 1 inode in use by using mv. (I know that regarding cpu usage and performance practically does not change) in that case I think we could use the current way, @errantepiphany, wdyt?

**Comment by errantepiphany** [comment]
@spolti I think the current way is fine. I don't see a reason to change it.

**Pull request closed without merging**
